CC = clang

CUSTOMCODEBLOCKS_FLAGS = -mavx2 -mlzcnt -O3
COMPILEROPTIMIZED_FLAGS = -O3
BENCHMARK_FLAGS = -g

BENCHMARKFILES_DIR ?= benchmark-files
CUSTOMBUILDS_DIR ?= builds/custom
COMPILERBUILDS_DIR ?= builds/compiler
OBJ_DIR ?= objects
CUSTOMCODEBLOCKS_DIR ?= custom-codeblocks
COMPILEROPTIMIZEDBLOCKS_DIR ?= compiler-optimized 

CUSTOMCODEBLOCKS_FILES := $(wildcard $(CUSTOMCODEBLOCKS_DIR)/*.h)

COMPILEROPTIMIZED_FILES := $(wildcard $(COMPILEROPTIMIZEDBLOCKS_DIR)/*.h)

CUSTOMCODEBLOCKS_BUILDS := $(patsubst $(CUSTOMCODEBLOCKS_DIR)/%.h,$(CUSTOMBUILDS_DIR)/%.o,$(CUSTOMCODEBLOCKS_FILES))

COMPILEROPTIMIZED_BUILDS := $(patsubst $(COMPILERBUILDS_DIR)/%.h,$(COMPILERBUILDS_DIR)/%.o,$(COMPILEROPTIMIZED_FILES))

buildcustom: $(CUSTOMCODEBLOCKS_BUILDS)
	echo $(CUSTOMCODEBLOCKS_FILES)

buildcompiler: $(COMPILEROPTIMIZED_BUILDS)
	echo $(COMPILEROPTIMIZED_FILES)

$(CUSTOMBUILDS_DIR)/%.o : $(CUSTOMCODEBLOCKS_DIR)/%.h
	$(CC) $(CUSTOMCODEBLOCKS_FLAGS) -c $< -o $@

$(COMPILERBUILDS_DIR)/%.o : $(COMPILEROPTIMIZEDBLOCKS_DIR)/%.h
	$(CC) $(COMPILEROPTIMIZED_FLAGS) -c $< -o $@

$(OBJ_DIR)/%.out : $(BENCHMARKFILES_DIR)/%.c
	$(CC) $(BENCHMARK_FLAGS) $(wildcard $(BUILDS_DIR)/*.o) $< -o $@

clean:
	rm -rf $(BUILDS_DIR)/*.out
	rm -rf $(OBJ_DIR)/*.out
